name: Bender Catalog

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    # Name the Job
    name: Test application
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install poetry
        uses: Gr1N/setup-poetry@v4

      - name: run tests
        run: |
          cd app
          poetry install
          poetry run pytest

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    needs: test
    if: github.ref == 'refs/heads/master'
    # Name the Job
    name: Build and publish docker image
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/cis188/hw4-testbed/unit4-fastapi:${{ github.sha }}
          context: app

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/cis188/hw4-testbed/unit4-cronjob:${{ github.sha }}
          context: cronjob

  deploy:
    name: Deploy latest version of code
    if: github.ref == 'refs/heads/master'
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: get kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name cis188 --role-arn arn:aws:iam::474844133309:role/dhaupt --alias cis188

      - name: deploy to cluster
        run: |
          helm upgrade --namespace dhaupt --install -f installation-values.yaml \
            --set cronjob.tag=${{ github.sha }} \
            --set fastapi.tag=${{ github.sha }} \
            aang ./bender-catalog
