name: ML Application Deployment

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Host Location'
        required: true
        default: 'heroku'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Push to Heroku
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_STAGING }}.git origin/master:master