name: Training Neural Network Model

on:
  push:
    branches:
      - train

jobs:
  installing:
    name: Installing Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Installing Python Dependencies
        run: pip install -r ./requirements_gpu.txt

      - name: Install PyTorch with GPU Acceleration
        run: pip install torch

  training:
    name: Training Model
    needs: installing
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Create Models Directory
        run: mkdir models
  
      - name: Run Training Script
        run: python train.py
        
      - name: Upload Trained Model
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'models'

  merge:
    name: Merge to Master Branch
    needs: installing
    runs-on: self-hosted
    steps:
      - name: Merge Train -> Master Branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}

  cleanup:
    name: Clean Artifacts
    runs-on: self-hosted
    steps:
      - name: Cleanup Docker
        if: ${{ always() }}
        run: docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}