name: Turing Evaluation Suite

on: [push]

jobs:
  install:
    name: Installing Python Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Installing Python Dependencies
        run: ls && pip install -r ./requirements.txt

      - name: Fetching Pre-Trained Language Model
        run: python -m spacy download en_core_web_trf