name: Turing Evaluation Suite

on:
  push:
    branches:
      - master

jobs:
  install:
    name: Installing Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Installing Python Dependencies
        run: pip install -r ./requirements_gpu.txt

  evaluate:
    name: Running Turing Evaluation on Model
    needs: install
    runs-on: self-hosted
    steps:
      - name: Clean Results Folder
        run:  rm -rf results && mkdir results
      - name: Generating Model Predictions
        run: python turing.py turing.txt
      
      - name: Upload Evaluation Results
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'results'
  clean:
    runs-on: self-hosted
    steps:
      - name: Cleanup Docker
        if: ${{ always() }}
        run: docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}