name: Turing Evaluation Suite

on:
  push:
    branches:
      - master

jobs:
  install:
    name: Installing Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Installing Python Dependencies
        run: pip install -r ./requirements.txt

  evaluate:
    name: Running Turing Evaluation on Model
    needs: install
    runs-on: self-hosted
    steps:
      - name: Generating Model Predictions
        run: python turing.py tests.json

  clean:
    runs-on: self-hosted
    steps:
      - name: Cleanup Docker
        if: ${{ always() }}
        run: docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}