name: Turing Evaluation Suite

on: [push]

jobs:
  install:
    name: Installing Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Installing Python Dependencies
        run: pip install -r ./requirements.txt

      - name: Fetching Pre-Trained Language Model
        run: python -m spacy download en_core_web_trf

      - name: Cleanup
        if: ${{ always() }}
        run: docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}

  evaluate:
    name: Running Turing Evaluation on Model
    needs: install
    runs-on: self-hosted
    steps:
      - name: Generating Model Predictions
        run: turing-188 generate tests.json